version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: mtg-nexus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mtg_nexus
      POSTGRES_USER: mtg_user
      POSTGRES_PASSWORD: mtg_password
    ports:
      - "5432:5432"
    volumes:
      - mtg_nexus_db:/var/lib/postgresql/data

volumes:
  mtg_nexus_db:
